theme: jekyll-theme-minimal

title: Curiosity Six
description: >
 This poem was submitted to the 2021 Conference on Artificial Life for its Art and ALife exhibition. The theme of the conference is "Robots: The century past and the century ahead." This poem imagines robots and artificial intelligence many centuries ahead, along with ideas of what it means to be human, to be in love, and to be finite. 